user www-data;
worker_processes auto; # Tells nginx to create one worker per CPU core
pid /run/nginx.pid;

events {
	worker_connections 768; # Max concurrent connections per worker
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##
	sendfile on; # → allows nginx to serve files efficiently
	tcp_nopush on; # → network optimization when sending large files (optional)
	types_hash_max_size 2048; # → internal optimization for MIME types
	# server_tokens off; # → hides nginx version in headers (security, optional)
	include /etc/nginx/mime.types; # → needed for correct Content-Type headers
	default_type application/octet-stream; # → fallback MIME type

	##
	# SSL Settings
	##
	ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	# ssl_prefer_server_ciphers on; # → tells nginx to pick server-preferred ciphers (good for prod, optional for dev)
    
	##
	# Logging Settings
	##
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;
    

    server {
		listen 443 ssl;
		listen [::]:443 ssl; # IPv6 support

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;

		# Tip for local dev / Inception:
		# You can use localhost or a fake domain like mysite.local
		# Map it in your host’s /etc/hosts so your browser can resolve it
		# Example /etc/hosts entry:
		# 127.0.0.1   mysite.local www.mysite.local
		server_name agallon.42.fr www.agallon.42.fr;


		root /var/www/html;
		index index.php;

		location / {
			try_files $uri $uri/ /index.php?$args; # try_files file1 file2 fallback;
		}

		location ~ [^/]\.php(/|$) {
			try_files $uri =404;
			include fastcgi_params; # includes default FastCGI parameters (QUERY_STRING, ...)
			fastcgi_pass wordpress:9000; # Forward to PHP container
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param HTTPS on;
		}

    }

	# HTTP redirection > https
	server {
		listen 80;
		listen [::]:80;
		return 301 https://$host$request_uri;
	}
}
