
version: "3.9"

services:
# docker build -t nginx -f ./requirements/nginx/Dockerfile
# docker run --name nginx -p 1234:443 --restart=always -env-file /path/to/env.txt --network this_network -v not needed?
  nginx:
    container_name: nginx
