# BASH CONTAINER
FROM debian:stable-slim
# or
# FROM from ubuntu:22.04
CMD ["bash"]


# # or from alpine:
# FROM alpine:latest
# # alpine doesnt have bash by default:
# RUN apk add --no-cache bash
# CMD ["bash"]

# then: docker run -it yourimage